export const pageContentSchema = {
  name: "pageContent",
  title: "Page Content",
  type: "document",
  fields: [
    {
      name: "pageKey",
      title: "Page Key",
      type: "string",
      options: {
        list: [
          { title: "Home", value: "home" },
          { title: "Home Two", value: "home-2" },
          { title: "Home Three", value: "home-3" },
          { title: "About Us", value: "about-us" },
          { title: "Contact Us", value: "contact-us" },
          { title: "FAQ", value: "faq" },
          { title: "Donate Us", value: "donate-us" },
          { title: "Become Volunteer", value: "become-volunteer" },
          { title: "Causes", value: "causes" },
          { title: "Events", value: "events" },
          { title: "Blog", value: "blog" },
          { title: "Our Team", value: "our-team" },
          { title: "Shop", value: "shop" },
        ],
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "banner",
      title: "Page Banner",
      type: "object",
      fields: [
        { name: "title", title: "Title", type: "string" },
        { name: "subtitle", title: "Subtitle", type: "text", rows: 3 },
        { name: "backgroundImage", title: "Background Image", type: "image", options: { hotspot: true } },
      ],
    },
    {
      name: "teamSection",
      title: "Team Section",
      type: "object",
      fields: [
        { name: "badge", title: "Badge", type: "string" },
        { name: "title", title: "Title", type: "string" },
      ],
    },
    {
      name: "donateSection",
      title: "Donate Intro Section",
      type: "object",
      fields: [
        { name: "badge", title: "Badge", type: "string" },
        { name: "title", title: "Title", type: "string" },
        { name: "description", title: "Description", type: "text", rows: 3 },
      ],
    },
    {
      name: "contactSection",
      title: "Contact Page Content",
      type: "object",
      fields: [
        { name: "infoBadge", title: "Info Badge", type: "string" },
        { name: "infoTitle", title: "Info Title", type: "string" },
        { name: "infoDescription", title: "Info Description", type: "text", rows: 3 },
        { name: "addressTitle", title: "Address Title", type: "string" },
        { name: "address", title: "Address", type: "string" },
        { name: "emailTitle", title: "Email Title", type: "string" },
        { name: "email", title: "Email", type: "string" },
        { name: "phoneTitle", title: "Phone Title", type: "string" },
        { name: "phone", title: "Phone", type: "string" },
        { name: "formTitle", title: "Form Title", type: "string" },
        { name: "successTitle", title: "Success Title", type: "string" },
        { name: "successMessage", title: "Success Message", type: "text", rows: 3 },
        { name: "resetButtonLabel", title: "Reset Button Label", type: "string" },
        { name: "submitButtonLabel", title: "Submit Button Label", type: "string" },
      ],
    },
    {
      name: "volunteerFormSection",
      title: "Volunteer Form Content",
      type: "object",
      fields: [
        { name: "badge", title: "Form Badge", type: "string" },
        { name: "title", title: "Form Title", type: "string" },
        { name: "description", title: "Form Description", type: "text", rows: 3 },
        { name: "successTitle", title: "Success Title", type: "string" },
        { name: "successMessage", title: "Success Message", type: "text", rows: 3 },
        { name: "resetButtonLabel", title: "Reset Button Label", type: "string" },
        { name: "submitButtonLabel", title: "Submit Button Label", type: "string" },
      ],
    },
  ],
};
